cm: 127.0.0.1/index.html
users:
  admin:
    endpoint: http://127.0.0.1:9000
    accesskey: test
    secretkey: Test2017
    ssl: false
    location: us-east-1
  cloud:
    endpoint: 127.0.0.1:9000
    accesskey: test
    secretkey: Test2017
    ssl: false
    location: us-east-1
buckets:
  jamieliu:
    mytest: rw
